// Generated by dts-bundle v0.7.3

declare module '@tenforce/toolbox-default-style' {
    export { Colors, ExtraColors, GrayscaleColors, ColorOption } from "@tenforce/toolbox-default-style/utils";
}

declare module '@tenforce/toolbox-default-style/utils' {
    export { Colors, ExtraColors, GrayscaleColors, ColorOption } from "@tenforce/toolbox-default-style/utils/colors";
}

declare module '@tenforce/toolbox-default-style/utils/colors' {
    export { GrayscaleColors } from "@tenforce/toolbox-default-style/utils/colors/GrayscalePalette";
    export { ExtraColors } from "@tenforce/toolbox-default-style/utils/colors/ExtraPalette";
    export { Colors } from "@tenforce/toolbox-default-style/utils/colors/Palette";
    export { ColorOption } from "@tenforce/toolbox-default-style/utils/colors/ColorOption";
}

declare module '@tenforce/toolbox-default-style/utils/colors/GrayscalePalette' {
    import { ColorOption } from "@tenforce/toolbox-default-style/utils/colors/ColorOption";
    export const GrayscaleColors: Record<string, ColorOption>;
}

declare module '@tenforce/toolbox-default-style/utils/colors/ExtraPalette' {
    import { ColorOption } from "@tenforce/toolbox-default-style/utils/colors/ColorOption";
    export const ExtraColors: Record<string, ColorOption>;
}

declare module '@tenforce/toolbox-default-style/utils/colors/Palette' {
    import { ColorOption } from "@tenforce/toolbox-default-style/utils/colors/ColorOption";
    export const Colors: Record<string, ColorOption>;
}

declare module '@tenforce/toolbox-default-style/utils/colors/ColorOption' {
    export interface ColorOption {
        name: string;
        background: string;
        text?: string;
        value: string;
        invertedValue?: string;
    }
}

